# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    branches:
      only:
        - master

    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:b8:8d:e6:cc:04:d9:6b:a9:57:aa:9c:5c:9d:07:fc"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}

      - run:
          name: publish
          command: |
            ./ci/publish.sh
      
      - save_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
