#!/bin/bash

set -e

CHART_NAME=primehub
CHART_ROOT=$(dirname "${BASH_SOURCE[0]}")/../$CHART_NAME
PROJECT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..

# it is registered into both circlie-ci and github
# by the way, circlie-ci only accept PEM private key format
# it should be generated by "ssh-keygen -m pem"
CI_PUBLISH_KEY=~/.ssh/id_rsa_0bb88de6cc04d96ba957aa9c5c9d07fc

source $PROJECT_ROOT/ci/common.sh

install::helm
install::chartpress

helm::workaround_rename
helm::update_dependency

ci::setup_ci_environment_and_publish
